name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'LICENSE'

jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "**/docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'
  lint:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: action/

      - run: |
          cd action
          npm ci || npm install
        shell: bash

      - run: |
          cd action
          npm run lint

  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-20.04
          - ubuntu-18.04
          - windows-2022
          - windows-2019
          - macos-11
          - macos-12
        version:
          - "5.9.0"
          - "5.15.2"
          - "6.2.0"
        cache:
          - cached
          - uncached

        # Ubuntu 18 is not a supported target for Qt 6: https://www.qt.io/blog/qt6-development-hosts-and-targets
        exclude:
          - os: ubuntu-18.04
            version: "6.2.0"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: action/

      - run: |
          cd action
          npm ci || npm install
        shell: bash

      - run: |
          cd action
          npm run build

      - name: Install Qt5 with options
        if: startsWith(matrix.version, '5')
        uses: ./
        with:
          modules: qtwebengine qtcharts
          version: ${{ matrix.version }}
          tools: tools_ifw tools_qtcreator,qt.tools.qtcreator
          cache: ${{ matrix.cache == 'cached' }}

      - name: Install Qt6 with options
        if: startsWith(matrix.version, '6.2')
        uses: ./
        with:
          # In Qt 6.2.0, qtwebengine requires qtpositioning and qtwebchannel
          modules: qtwebengine qtpositioning qtwebchannel qtcharts
          version: ${{ matrix.version }}
          tools: tools_ifw tools_qtcreator,qt.tools.qtcreator
          cache: ${{ matrix.cache == 'cached' }}

      - name: Configure project on windows
        if: startsWith(matrix.os, 'windows')
        env:
          QT_VERSION: ${{ matrix.version }}
        run: |
          cd code
          for /f "delims=" %%d in ( 'vswhere.exe -latest -property installationPath' ) do @( call "%%d\VC\Auxiliary\Build\vcvars64.bat" )
          IF "%QT_VERSION:~0,1%"=="5" ( dir %Qt5_DIR%\lib\cmake ) ELSE ( dir %Qt6_DIR%\lib\cmake )
          qmake ..
        shell: cmd

      - name: Configure project on unix
        if: (!startsWith(matrix.os, 'windows'))
        env:
          QT_VERSION: ${{ matrix.version }}
        run: |
          cd code
          if [[ $QT_VERSION == 6* ]]; then
            ls "$Qt6_DIR/lib/cmake"
          else
            ls "$Qt5_DIR/lib/cmake"
          fi
          qmake ..
        shell: bash
